addons:
  apt:
    packages:
      zsh
dist: trusty
install:
  - npm install -g jsonlint
  - mkdir .bin
  - curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > .bin/revolver
  - curl -L https://raw.githubusercontent.com/molovo/color/master/color.zsh > .bin/color
  - curl -L https://github.com/molovo/zunit/releases/download/v0.6.3/zunit > .bin/zunit
  - chmod u+x .bin/{color,revolver,zunit}
  - export PATH="$PWD/.bin:$PATH"
script:
  - zunit
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
